language: java
sudo: required
dist: trusty
group: edge

addons:
  sonarcloud:
    organization: "trellis-ldp"
    token:
      secure: "fGWpdWz1Dq7b5jDKKoZLE+wQFZlwzk8siLD9TXHqdy0x7s/hgaxmpAb05Tgob1GMgqDjGGheYZ3Ig/YZBo68N8/oLOFiBMFu8a5J+4Lkw9IjLsfGml5KwZV3e9DyQkYbC9sTX4sEl0+ERnpi0ukBWWRiKDxF1OQaSgZXBc/hQjEAb3+tZrukLgaMpI8aEgL6kCziEdZycfDLcCjE5p50pEyPHn3OZbelAgBGFiYehSvC0gkt7djvBUd7tGeU6cvzvBGvPGJZmDZvWOg7igEyZZ7/PGKnFnPvBk8i7j17Xm8FrFxGaYZkgHZuU7aAHoM/ySgORo42vsZr1DxPZOIBbLEIqm6gGXNCCyVNinDks8j9kglGGzOw0Wjv86O12JyII7S8k1Ab1dKymDvOm326keku5ucLrQtAxOCpaz4TtqiowFB/JGlGiB+s3HoDsbsG8tk4bjWFsGa5cXcyZ/zKgwqKCjhE9WL6+dtcBZc2rsGUp5lwDQ7aMPi6dbPKKgEKRQKj5buzXdw5fqgq5Ht0Q2CCxp5QrlQWCgtlLVRysvNnPO8bnnJSvKV4tKHO4LDt+6YOG/zJEK9SjLXm2kLU+zczl684nwDkQo1CXU2wiKZnhUYiWfvJ1J/Yy3SDj0XVc8CRWkiVx4B63NI98yhY1yrlJhtqPuDMiXgfQZxsMDw="

matrix:
  fast_finish: true

install: true

script:
- . ./buildtools/src/install/install-jdk-10.sh
- . ./buildtools/src/install/install-jpms.sh

after_success:
  - ./gradlew jacocoRootReport && bash <(curl -s https://codecov.io/bash) || true

branches:
  only:
    - master
    - jpms

env:
  global:
    - CODECOV_TOKEN=aebd5e75-ee4d-4ad9-aa21-0abffe315df2